---
- name: Include host vars {{ ansible_distribution + ansible_distribution_major_version }}
  ansible.builtin.include_vars: host_{{ ansible_distribution + ansible_distribution_major_version }}.yml

- name: Include iso
  ansible.builtin.include_vars: group_vars/iso.yml

- name: Check if virt-sparsify is present
  ansible.builtin.stat:
    path: /usr/bin/virt-sparsify
  register: sparsify

- name: Ensure virt-sparsify is present
  ansible.builtin.assert:
    that: sparsify['stat']['exists']
    fail_msg: I need the virt-sparsify binary, check if guestfs-tools rpm is installed

- name: Get libvirt pool names
  community.libvirt.virt_pool:
    command: facts

- name: Refresh libvirt pool facts
  community.libvirt.virt_pool:
    command: refresh
    name: "{{ pool['key'] }}"
  loop: "{{ ansible_libvirt_pools | dict2items }}"
  loop_control:
    loop_var: pool

- name: Find current vms
  community.libvirt.virt:
    command: list_vms
  register: current_vms
  changed_when: false

- name: Define guests
  ansible.builtin.include_tasks:
    file: define_guests.yml
  loop: "{{ vms }}"
  loop_control:
    loop_var: guest
  when: vms is defined

- name: Ensure vms is a hostvar
  ansible.builtin.set_fact:
    vms: "{{ vms }}"
  when: vms is defined

- name: Create guests definition
  ansible.builtin.include_tasks:
    file: define_guests.yml
  vars:
    guest: "{{ os_image }}"
  when: os_image is defined

- name: Show {{ guests }}
  ansible.builtin.debug:
    var: guests

- name: Show current vms
  ansible.builtin.debug:
    var: current_vms['list_vms']
