---
- name: include host {{ ansible_distribution }}{{ ansible_distribution_major_version }} vars
  include_vars: host_{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml

- name: include iso
  include_vars: group_vars/iso.yml

- name: check if virt-sparsify is present
  stat:
    path: /usr/bin/virt-sparsify
  register: sparsify

- name: ensure virt-sparsify is present
  assert:
    that: sparsify['stat']['exists']
    fail_msg: I need the virt-sparsify binary, check if guestfs-tools rpm is installed

- name: get libvirt pool names
  community.libvirt.virt_pool:
    command: facts

- name: refresh libvirt pool facts
  community.libvirt.virt_pool:
    command: refresh
    name: "{{ pool['key'] }}"
  loop: "{{ ansible_libvirt_pools | dict2items }}"
  loop_control:
    loop_var: pool

- name: find current vms
  community.libvirt.virt:
    command: list_vms
  register: current_vms
  changed_when: false

- name: define guests
  include_tasks:
    file: define_guests.yml
  loop: "{{ vms }}"
  loop_control:
    loop_var: guest
  when: vms is defined

- name: ensure vms is a hostvar
  set_fact:
    vms: "{{ vms }}"
  when: vms is defined

- name: create guests definition
  include_tasks:
    file: define_guests.yml
  vars:
    guest: "{{ os_image }}"
  when: os_image is defined

- name: show {{ guests }}
  debug:
    var: guests

- name: show current vms
  debug:
    var: current_vms['list_vms']
