---
- name: Set readable vars
  ansible.builtin.set_fact:
    dev: "{{ device['key'] }}"

- name: Set pool of the specified image
  ansible.builtin.include_tasks: set_image_pool.yml
  when:
    - guests[guest]['guest_def']['devices']['storage'][dev]['image'] is defined
    - guests[guest]['guest_def']['devices']['storage'][dev]['pool'] is not defined

- name: Set backing_image_pool of the specified backing_image
  ansible.builtin.include_tasks: set_backing_image_pool.yml
  when:
    - guests[guest]['guest_def']['devices']['storage'][dev]['backing_image'] is defined
    - guests[guest]['guest_def']['devices']['storage'][dev]['backing_image_pool'] is not defined

- name: Set device pool
  ansible.builtin.set_fact:
    guests: "{{ guests | combine({guest: {'guest_def': {'devices': {'storage': {dev: {'pool': 'default'}}}}}}, recursive=True) }}"
  when: guests[guest]['guest_def']['devices']['storage'][dev]['pool'] is not defined

- name: Set image
  ansible.builtin.set_fact:
    image: "{{ guest | lower | replace('.', '_') }}_{{ dev }}.qcow2"

- name: Set device image name
  ansible.builtin.set_fact:
    guests: "{{ guests | combine({guest: {'guest_def': {'devices': {'storage': {dev: {'image': image}}}}}}, recursive=True) }}"
  when: guests[guest]['guest_def']['devices']['storage'][dev]['image'] is not defined

- name: Set type to cdrom
  ansible.builtin.set_fact:
    guests: "{{ guests | combine({guest: {'guest_def': {'devices': {'storage': {dev: {'type': 'cdrom', 'method': 'keep'}}}}}}, recursive=True) }}"
  when:
    - guests[guest]['guest_def']['devices']['storage'][dev]['type'] is not defined
    - guests[guest]['guest_def']['devices']['storage'][dev]['image'] | regex_search('.*iso$', ignorecase=True)

- name: Set type to disk
  ansible.builtin.set_fact:
    guests: "{{ guests | combine({guest: {'guest_def': {'devices': {'storage': {dev: {'type': 'disk'}}}}}}, recursive=True) }}"
  when:
    - guests[guest]['guest_def']['devices']['storage'][dev]['type'] is not defined
    - guests[guest]['guest_def']['devices']['storage'][dev]['image'] | regex_search('.*qcow2$')

- name: Set device method to create
  ansible.builtin.set_fact:
    guests: "{{ guests | combine({guest: {'guest_def': {'devices': {'storage': {dev: {'method': 'create'}}}}}}, recursive=True) }}"
  when:
    - guests[guest]['guest_def']['devices']['storage'][dev]['backing_image'] is not defined
    - guests[guest]['guest_def']['devices']['storage'][dev]['method'] is not defined

- name: Set device method to clone
  ansible.builtin.set_fact:
    guests: "{{ guests | combine({guest: {'guest_def': {'devices': {'storage': {dev: {'method': 'clone'}}}}}}, recursive=True) }}"
  when:
    - guests[guest]['guest_def']['devices']['storage'][dev]['backing_image'] is defined
    - guests[guest]['guest_def']['devices']['storage'][dev]['method'] is not defined

- name: Set device bootable
  ansible.builtin.set_fact:
    guests: "{{ guests | combine({guest: {'guest_def': {'devices': {'storage': {dev: {'bootable': false}}}}}}, recursive=True) }}"
  when: guests[guest]['guest_def']['devices']['storage'][dev]['bootable'] is not defined
