---
- name: set {{ dev }} pool if image already exists
  set_fact:
    guests: >-
      {{
        guests | combine(
          { guest: { 'guest_def': { 'devices': { 'storage': { dev: { 'backing_image_pool': loop_name['key'] }}}}}},
          recursive=True
        )
      }}
  loop: "{{ ansible_libvirt_pools | dict2items }}"
  loop_control:
    loop_var: loop_name
  when: guests[guest]['guest_def']['devices']['storage'][dev]['backing_image'] in loop_name['value']['volumes']

- name: set {{ dev }} pool to default
  set_fact:
    guests: >-
      {{
        guests | combine(
          { guest: { 'guest_def': { 'devices': { 'storage': { dev: { 'backing_image_pool': 'default' }}}}}},
          recursive=True
        )
      }}
  when: guests[guest]['guest_def']['devices']['storage'][dev]['backing_image_pool'] is not defined
