---
local_repo_url: http://repo.linux.lab/
root_pubkey: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
ipa_domain: linux.lab
ipa_realm: "{{ ipa_domain | upper }}"
root_password: linuxlab  # encrypt this in production
