---
ipaserver_auto_reverse: true
ipaserver_auto_forwarders: true
ipaserver_setup_dns: true
ipaserver_domain: "{{ ipa_domain }}"
ipaserver_realm: '{{ ipa_realm }}'
ipaclient_mkhomedir: true
ipaclient_no_ntp: true
ipaautomount_location: default
ipaadmin_password: rockylinux
# the dm password may not contain '\'
ipadm_password: rockylinux
