---
# installer role options
foreman_installer_command: foreman-installer
foreman_installer_package: foreman-installer-katello
foreman_installer_scenario: katello
foreman_installer_verbose: true
foreman_installer_no_colors: false
foreman_installer_option_org: "ZolderCloud Lab"
foreman_installer_option_loc: "zolder"
foreman_installer_option_admin: admin
foreman_installer_option_admin_password: katello42  # encrypt this in production
foreman_enable_remote_execution: true

foreman_enable_ansible: true
foreman_enable_compute_libvirt: true

theforeman_release: '3.0'
katello_release: '4.2'

katello_repos:
  - https://yum.theforeman.org/releases/{{ theforeman_release }}/el{{ ansible_distribution_major_version }}/x86_64/foreman-release.rpm
  - https://yum.theforeman.org/katello/{{ katello_release }}/katello/el{{ ansible_distribution_major_version }}/x86_64/katello-repos-latest.rpm
  - centos-release-ansible-29
  - https://yum.puppet.com/puppet6-release-el-{{ ansible_distribution_major_version }}.noarch.rpm

dnf_modules:
  - name: ruby
    version: 2.7
    profiles: ''

  - name: postgresql
    version: 12
    profiles: ''

centos_repos:
  - name: powertools
    repofile: CentOS-Linux-PowerTools.repo

foreman_install_cmd: >-
  env LANG=en_US.UTF-8 LC_ALL=en_US.UTF8
  {{ foreman_installer_command }}
  --scenario {{ foreman_installer_scenario }}
  {{ (foreman_installer_verbose|bool) | ternary("-v", "") }}
  {{ (foreman_installer_no_colors|bool) | ternary("--no-colors", "") }}
  --detailed-exitcodes
