---
- name: delete previous attempts
  include_role:
    name: RobVerduijn.lab.delete_guest

- name: create cfg iso
  include_role:
    name: RobVerduijn.lab.create_cfg_iso
  vars:
    method: create_backing_image
  loop: "{{ guests | dict2items }}"
  loop_control:
    loop_var: guest

- name: create qcow2 image
  include_role:
    name: RobVerduijn.lab.create_storage_qcow
  loop: "{{ guests | dict2items }}"
  loop_control:
    loop_var: guest

- name: define {{ os_image }}
  include_role:
    name: RobVerduijn.lab.define_guest
  loop: "{{ guests | dict2items }}"
  loop_control:
    loop_var: guest

- name: ensure {{ os_image }} is started
  community.libvirt.virt:
    name: "{{ os_image }}"
    state: running

- name: set guest key
  set_fact:
    guest: "{{ {} | combine({ 'key': os_image }) }}"

- name: add {{ os_image }} to inventory
  include_role:
    name: add_guest_to_inventory

- name: include {{ guests[os_image]['guest_def']['dist_family'] }}
  include_tasks: "{{ guests[os_image]['guest_def']['dist_family'] }}.yml"

- name: sysprep image
  include_role:
    name: RobVerduijn.lab.sparsify_image
