---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts['packages'] is not defined

- name: Ensure dnf-utils is installed
  ansible.builtin.package:
    name: dnf-utils
    state: present
  when: "'dnf-utils' not in ansible_facts['packages'].keys()"

- name: Check reboot needed
  ansible.builtin.command: needs-restarting -r
  register: needs_restarting
  changed_when: false
  failed_when: needs_restarting['rc'] > 1

- name: Reboot
  ansible.builtin.reboot:
  when: needs_restarting['rc'] | default(0) == 1
