---
ansible_python_interpreter: /usr/bin/python3

local_repo_url: http://repo.tjako.thuis/
root_pubkey: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
ipa_domain: linux.lab
ipa_realm: "{{ ipa_domain | upper }}"

# I suggest you keep the stuff below in the file group_vars/all/secrets.yml

# which will be included because it is in the group_vars/all folder
# don't forget to add it to your .gitignore
#
# redhat_login: my_redhat_login
# redhat_password: my_redhat_password
# pool_id: my_pool_id

root_password: linuxlab  # encrypt this in production
administrator: Admin
administrator_password: windowslab  # encrypt this in production

timesync_ntp_servers:
  - hostname: 0.fedora.pool.ntp.org
    iburst: true
  - hostname: 1.fedora.pool.ntp.org
    iburst: true
  - hostname: 2.fedora.pool.ntp.org
    iburst: true
  - hostname: 3.fedora.pool.ntp.org
    iburst: true