---
- name: Set timezone to 'W. Europe Standard Time' (GMT+01:00)
  community.windows.win_timezone:
    timezone: "{{ timezone }}"

- name: set location format and unicode
  community.windows.win_region:
    format: "{{ format }}"
    location: "{{ location }}"
    unicode_language: "{{ unicode_language }}"
  register: region_result

- name: reboot
  ansible.windows.win_reboot:
    post_reboot_delay: '60'
    reboot_timeout: '1800'
  when: region_result.restart_required
