---
- name: run foreman installer to {{ (foreman_plugin_enable_ansible|bool) | ternary("enable", "disable") }} ansible
  command: >-
      {{ foreman_install_cmd }}
      {{ (foreman_plugin_enable_ansible|bool) | ternary("--enable-foreman-plugin-ansible", "--no-enable-foreman-plugin-ansible") }}
      {{ (foreman_plugin_enable_ansible|bool) | ternary("--enable-foreman-proxy-plugin-ansible", "--no-enable-foreman-proxy-plugin-ansible") }}
  register: foreman_installer_run
  changed_when: foreman_installer_run['rc'] == 2
  failed_when: foreman_installer_run['rc'] not in [0, 2]
