---
- name: Add content credential
  theforeman.foreman.content_credential:
    password: "{{ foreman_installer_option_admin_password }}"
    server_url: https://{{ inventory_hostname }}
    username: "{{ foreman_installer_option_admin }}"
    validate_certs: false
    name: "{{ product['gpg_key_name'] }}"
    content_type: gpg_key
    organization: "{{ foreman_installer_option_org }}"
    content: "{{ product['gpg_key'] }}"
  loop: "{{ products }}"
  loop_control:
    loop_var: product

- name: Add sync plan
  theforeman.foreman.sync_plan:
    password: "{{ foreman_installer_option_admin_password }}"
    server_url: https://{{ inventory_hostname }}
    username: "{{ foreman_installer_option_admin }}"
    validate_certs: false
    name: Daily Sync
    organization: "{{ foreman_installer_option_org }}"
    interval: "daily"
    enabled: false
    sync_date: "2023-01-01 00:00:00 UTC"
    state: present

- name: Add product
  theforeman.foreman.product:
    password: "{{ foreman_installer_option_admin_password }}"
    server_url: https://{{ inventory_hostname }}
    username: "{{ foreman_installer_option_admin }}"
    validate_certs: false
    name: "{{ product['name'] }}"
    organization: "{{ foreman_installer_option_org }}"
    sync_plan: Daily Sync
    gpg_key: "{{ product['gpg_key_name'] }}"
    state: present
  loop: "{{ products }}"
  loop_control:
    loop_var: product

- name: Create repository
  theforeman.foreman.repository:
    password: "{{ foreman_installer_option_admin_password }}"
    server_url: https://{{ inventory_hostname }}
    username: "{{ foreman_installer_option_admin }}"
    validate_certs: false
    name: "{{ product[1]['name'] }}"
    product: "{{ product[0]['name'] }}"
    url: "{{ product[1]['url'] }}"
    content_type: "yum"
    download_policy: on_demand
    organization: "{{ foreman_installer_option_org }}"
    state: present
  loop: "{{ products | subelements('repositories') }}"
  loop_control:
    loop_var: product

- name: Sync repository
  theforeman.foreman.repository_sync:
    password: "{{ foreman_installer_option_admin_password }}"
    server_url: https://{{ inventory_hostname }}
    username: "{{ foreman_installer_option_admin }}"
    validate_certs: false
    repository: "{{ product[1]['name'] }}"
    product: "{{ product[0]['name'] }}"
    organization: "{{ foreman_installer_option_org }}"
  loop: "{{ products | subelements('repositories') }}"
  loop_control:
    loop_var: product
  when: sync_repos | default(true) | bool

- name: Add a production lifecycle environment
  theforeman.foreman.lifecycle_environment:
    password: "{{ foreman_installer_option_admin_password }}"
    server_url: https://{{ inventory_hostname }}
    username: "{{ foreman_installer_option_admin }}"
    validate_certs: false
    name: "{{ lifecycle['name'] }}"
    organization: "{{ foreman_installer_option_org }}"
    prior: "{{ lifecycle['prior'] }}"
    state: "present"
  loop: "{{ lifecycles }}"
  loop_control:
    loop_var: lifecycle

- name: Define content_view
  ansible.builtin.include_tasks: contentview.yml
  loop: "{{ products }}"
  loop_control:
    loop_var: product

- name: Create content view  # noqa: args[module]
  theforeman.foreman.content_view:
    password: "{{ foreman_installer_option_admin_password }}"
    server_url: https://{{ inventory_hostname }}
    username: "{{ foreman_installer_option_admin }}"
    validate_certs: false
    name: "{{ content_view['name'] }}"
    organization: "{{ foreman_installer_option_org }}"
    repositories: "{{ content_view['repositories'] }}"
  loop: "{{ content_views }}"
  loop_control:
    loop_var: content_view

- name: Ensure content view version 1.0 is published
  theforeman.foreman.content_view_version:
    password: "{{ foreman_installer_option_admin_password }}"
    server_url: https://{{ inventory_hostname }}
    username: "{{ foreman_installer_option_admin }}"
    validate_certs: false
    content_view: "{{ content_view['name'] }}"
    organization: "{{ foreman_installer_option_org }}"
    version: 1.0
    lifecycle_environments:
      - Library
      - Test
      - Productie
  loop: "{{ content_views }}"
  loop_control:
    loop_var: content_view

- name: Create activation key
  theforeman.foreman.activation_key:
    password: "{{ foreman_installer_option_admin_password }}"
    server_url: https://{{ inventory_hostname }}
    username: "{{ foreman_installer_option_admin }}"
    validate_certs: false
    name: "{{ content_view['name'] | replace('cv', 'ak') }}"
    organization: "{{ foreman_installer_option_org }}"
    lifecycle_environment: "Library"
    content_view: "{{ content_view['name'] }}"
    # subscriptions:
    #   - name: "{{ content_view['name'] }}"
    auto_attach: true
  loop: "{{ content_views }}"
  loop_control:
    loop_var: content_view
