---
# according to the installer 'True' is not a boolean hence the lower filter
- name: run foreman installer to {{ (foreman_plugin_enable_discovery|bool) | ternary("enable", "disable") }} discovery
  command: >-
      {{ foreman_install_cmd }}
      {{ (foreman_plugin_enable_discovery | ternary("--enable-foreman-plugin-discovery", "--no-enable-foreman-plugin-discovery")) }}
      {{ (foreman_plugin_enable_discovery | ternary("--enable-foreman-proxy-plugin-discovery", "--no-enable-foreman-proxy-plugin-discovery")) }}
      --foreman-proxy-plugin-discovery-install-images {{ (foreman_plugin_enable_discovery | ternary("true", "false")) }}
  register: foreman_installer_run
  changed_when: foreman_installer_run['rc'] == 2
  failed_when: foreman_installer_run['rc'] not in [0, 2]
  notify:
    - restart foreman-proxy
