---
# according to the installer 'True' is not a boolean hence the lower filter
- name: run foreman installer to {{ (foreman_proxy_dns|bool) | ternary("enable", "disable") }} dns
  command: >-
      {{ foreman_install_cmd }}
      --foreman-proxy-dns {{ foreman_proxy_dns | lower }}
      --foreman-proxy-dns-provider {{ foreman_proxy_dns_provider | default('nsupdate') }}
      --foreman-proxy-dns-reverse {{ foreman_proxy_dns_reverse }}
      --foreman-proxy-dns-server {{ foreman_proxy_dns_server | default('127.0.0.1') }}
  register: foreman_installer_run
  changed_when: foreman_installer_run['rc'] == 2
  failed_when: foreman_installer_run['rc'] not in [0, 2]
  notify:
    - restart foreman-proxy
