---
- name: Computer resource libvirt plugin
  ansible.builtin.include_tasks: compute_resource_libvirt.yml
  when: foreman_plugin_enable_compute_libvirt | default(false) | bool

- name: Configure proxies
  ansible.builtin.include_tasks: proxies.yml
  when: foreman_configure_proxies | default(false) | bool

- name: Configure domain
  theforeman.foreman.domain:
    password: "{{ foreman_installer_option_admin_password }}"
    server_url: https://{{ inventory_hostname }}
    username: "{{ foreman_installer_option_admin }}"
    validate_certs: false
    name: "{{ ipa_domain }}"
    dns_proxy: "{{ inventory_hostname }}"
    locations:
      - "{{ foreman_installer_option_loc }}"
    organizations:
      - "{{ foreman_installer_option_org }}"
    state: present
  when:
    - foreman_configure_proxies | default(false) | bool
    - foreman_configure_dns | default(false) | bool
    - foreman_configure_domain | default(false) | bool

- name: Linux.lab subnet
  theforeman.foreman.subnet:
    password: "{{ foreman_installer_option_admin_password }}"
    server_url: https://{{ inventory_hostname }}
    username: "{{ foreman_installer_option_admin }}"
    validate_certs: false
    name: "{{ ipa_domain }}"
    description: "{{ ipa_domain }} {{ foreman_installer_option_org }} {{ foreman_installer_option_loc }}"
    network: "{{ foreman_proxy_dhcp_network }}"
    mask: "{{ foreman_proxy_dhcp_netmask }}"
    gateway: "{{ foreman_proxy_dhcp_gateway }}"
    from_ip: "{{ foreman_proxy_dhcp_range_start }}"
    to_ip: "{{ foreman_proxy_dhcp_range_stop }}"
    boot_mode: "DHCP"
    dhcp_proxy: "{{ inventory_hostname }}"
    discovery_proxy: "{{ inventory_hostname }}"
    dns_proxy: "{{ inventory_hostname }}"
    dns_primary: "{{ (foreman_proxy_dhcp_nameservers.split(','))[0] }}"
    remote_execution_proxies: "{{ inventory_hostname }}"
    tftp_proxy: "{{ inventory_hostname }}"
    domains:
      - "{{ ipa_domain }}"
    organizations:
      - "{{ foreman_installer_option_org }}"
    locations:
      - "{{ foreman_installer_option_loc }}"
    state: present
  when:
    - foreman_configure_proxies | default(false) | bool
    - foreman_proxy_dns | default(false) | bool
    - foreman_configure_domain | default(false) | bool
    - foreman_proxy_dhcp | default(false) | bool
    - foreman_proxy_tftp | default(false) | bool
