---
- name: check if foreman is already installed
  stat:
    path: /etc/foreman-installer/scenarios.d/.installed
  register: installed_file

# I've split up the installation task into small tasks
# This takes more time to complete but some plugins/features simply will
# crash the installer if they are configured at the same time

- name: install foreman
  include_tasks: install.yml
  when: not installed_file['stat']['exists']

- name: configure infrastructure
  include_tasks: infrastructure.yml
  when:
    - foreman_configure_infrastructure is defined
    - foreman_configure_infrastructure | bool

- name: content
  include_tasks: content.yml
  when:
    - foreman_configure_content is defined
    - foreman_configure_content | bool

- name: configure hosts
  include_tasks: hosts.yml
  when:
    - foreman_configure_hosts is defined
    - foreman_configure_hosts | bool

- name: configure
  include_tasks: configure.yml
  when:
    - foreman_configure_configure is defined
    - foreman_configure_configure | bool
