---
- name: Check if foreman is already installed
  ansible.builtin.stat:
    path: /etc/foreman-installer/scenarios.d/.installed
  register: installed_file

# I've split up the installation task into small tasks
# This takes more time to complete but some plugins/features simply will
# crash the installer if they are configured at the same time

- name: Install foreman
  ansible.builtin.include_tasks: install.yml
  when: not installed_file['stat']['exists']

- name: Configure infrastructure
  ansible.builtin.include_tasks: infrastructure.yml
  when: foreman_configure_infrastructure | default(false) | bool

- name: Content
  ansible.builtin.include_tasks: content.yml
  when: foreman_configure_content | default(false) | bool

- name: Configure provisioning
  ansible.builtin.include_tasks: provisioning.yml
  when: foreman_configure_provisioning | default(false) | bool

- name: Configure
  ansible.builtin.include_tasks: hostgroup.yml
  when: foreman_configure_hostgroup | default(false) | bool
