---
# according to the installer 'True' is not a boolean hence the lower filter
- name: run foreman installer to {{ (foreman_proxy_tftp|bool) | ternary("enable", "disable") }} tftp
  command: >-
      {{ foreman_install_cmd }}
      --foreman-proxy-tftp {{ foreman_proxy_tftp | lower }}
      --foreman-proxy-tftp-servername {{ foreman_proxy_tftp_server_name }}
  register: foreman_installer_run
  changed_when: foreman_installer_run['rc'] == 2
  failed_when: foreman_installer_run['rc'] not in [0, 2]
  notify:
    - restart foreman-proxy
