---
orgs:
  - name: Zolder Cloud Lab
    description: Mijn persoonlijke hobby omgeving
    label: Zolder_Cloud_Lab

locations:
  - name: zolder
    description: zoldercloud data center
    organizations:
      - Zolder Cloud Lab

katello_hosts:
  - name: "{{ inventory_hostname }}"
    environment: production
    location: zolder
    organization: Zolder Cloud Lab

# default organization and location anchor
def_loc_org: &loc_org
  locations:
    - zolder
  organizations:
    - Zolder Cloud Lab

# we don't use puppet but things will break if we don't do this
puppet_environments:
  - name: production
    <<: *loc_org

smart_proxies:
  - name: "{{ inventory_hostname }}"
    <<: *loc_org

realms:
  - name: "{{ ipa_realm }}"
    realm_proxy: "{{ inventory_hostname }}"
    realm_type: FreeIPA
    <<: *loc_org

domains:
  - name: "{{ ipa_domain }}"
    description: "{{ ipa_domain }}"
    dns_proxy: "{{ inventory_hostname }}"
    <<: *loc_org

compute_resources:
  - name: twoflowers.tjako.thuis
    provider: libvirt
    provider_params:
      url: qemu+ssh://{{ groups['buildhost'][0] }}/system
      display_type: spice
    <<: *loc_org

subnets:
  - name: test_lan
    description: test_lan
    network: "{{ network[0]['ip']['address'][0] | ipaddr('network') }}"
    mask: "{{ network[0]['ip']['address'][0] | ipaddr('netmask') }}"
    boot_mode: DHCP
    dns_primary: "{{ network[0]['ip']['dns'] | join(' ') }}"
    gateway: "{{ network[0]['ip']['gateway4']  }}"
    ipam: DHCP
    from_ip: "{{ katello_dhcp_range_start }}"
    to_ip: "{{ katello_dhcp_range_stop }}"
    domains:
      - "{{ ipa_domain }}"
    dhcp_proxy: "{{ inventory_hostname }}"
    tftp_proxy: "{{ inventory_hostname }}"
    dns_proxy: "{{ inventory_hostname }}"
    template_proxy: "{{ inventory_hostname }}"
    remote_execution_proxies:
      - "{{ inventory_hostname }}"
    <<: *loc_org
