---
# minimal installer role options
foreman_installer_command: foreman-installer
foreman_installer_package: foreman-installer-katello
foreman_installer_scenario: katello
foreman_installer_verbose: true
foreman_installer_no_colors: false
# optional installer options (commment to disable them)
foreman_installer_option_org: "{{ orgs[0]['name'] }}"
foreman_installer_option_loc: "{{ locations[0]['name'] }}"
foreman_installer_option_admin: admin
foreman_installer_option_admin_password: katello42  # encrypt this in production
# optional plugins set to false to disable them
foreman_plugin_enable_remote_execution_ssh: true
foreman_plugin_enable_ansible: true  # requires the remote-exection-ssh plugin
foreman_plugin_enable_compute_libvirt: true

# the configurations below are set to false so you can
# use the environment to practice
# if you don't care for such set the desired options to true

# katello use local dns
foreman_proxy_dns: false
foreman_proxy_dns_reverse: "{{ (network[0]['ip']['address'][0] | ansible.netcommon.ipaddr('revdns')).split('.')[1:-1] | join('.') }}"

# katello use local dhcp
foreman_proxy_dhcp: false
foreman_proxy_dhcp_gateway: "{{ network[0]['ip']['gateway4'] }}"
foreman_proxy_dhcp_nameservers: "{{ network[0]['ip']['dns'] | join(',') }}"
foreman_proxy_dhcp_netmask: "{{ network[0]['ip']['address'][0] | ansible.netcommon.ipaddr('netmask') }}"
foreman_proxy_dhcp_network: "{{ network[0]['ip']['address'][0] | ansible.netcommon.ipaddr('network') }}"
foreman_proxy_dhcp_range_start: "{{ ( network[0]['ip']['address'][0] | ansible.netcommon.ipaddr('address')).split('.')[:-1] | join('.') }}.150"
foreman_proxy_dhcp_range_stop: "{{ ( network[0]['ip']['address'][0] | ansible.netcommon.ipaddr('address')).split('.')[:-1] | join('.') }}.254"
foreman_proxy_dhcp_range: "{{ foreman_proxy_dhcp_range_start }} {{ foreman_proxy_dhcp_range_stop }}"
foreman_proxy_dhcp_search_domains: "{{ ipa_domain }}"

# katello use local tftp
foreman_proxy_tftp: false
foreman_proxy_tftp_server_name: "{{ network[0]['ip']['address'][0] }}"

# katello use discovery plugin
foreman_plugin_enable_discovery: false

# you probably don't need to edit the vars below
theforeman_release: '3.0'
katello_release: '4.2'

katello_repos:
  - https://yum.theforeman.org/releases/{{ theforeman_release }}/el{{ ansible_distribution_major_version }}/x86_64/foreman-release.rpm
  - https://yum.theforeman.org/katello/{{ katello_release }}/katello/el{{ ansible_distribution_major_version }}/x86_64/katello-repos-latest.rpm
  - centos-release-ansible-29
  - https://yum.puppet.com/puppet6-release-el-{{ ansible_distribution_major_version }}.noarch.rpm

dnf_modules:
  - name: ruby
    version: 2.7
    profiles: ''

  - name: postgresql
    version: 12
    profiles: ''

centos_repos:
  - name: powertools
    repofile: CentOS-Linux-PowerTools.repo

foreman_install_cmd: >-
  env LANG=en_US.UTF-8 LC_ALL=en_US.UTF8
  {{ foreman_installer_command }}
  --scenario {{ foreman_installer_scenario }}
  {{ (foreman_installer_verbose|bool) | ternary("-v", "") }}
  {{ (foreman_installer_no_colors|bool) | ternary("--no-colors", "") }}
  --detailed-exitcodes


katello_users:
  - name: foreman
    comment: Foreman
    uid: 1014
    gid: 1014
    home: /usr/share/foreman
    shell: /bin/false

  - name: foreman-proxy
    comment: Foreman Proxy daemon user
    uid: 1015
    gid: 1015
    home: /usr/share/foreman-proxy
    shell: /bin/false

errata_packages:
  - pulp-admin-client
  - pulp-rpm-admin-extensions

# - rubygem-smart_proxy_dhcp_remote_isc
# - tfm-rubygem-foreman_discovery

katello_keytabs:
  foremanproxy:
    principal: '{{ "foremanproxy/" + ansible_fqdn + "@" + ipa_realm }}'
    keytab: /etc/foreman-proxy/dns.keytab
    user: foreman-proxy
    group: foreman-proxy
    notify: restart foreman-proxy
    type: service
  HTTP:
    principal: '{{ "HTTP/" + ansible_fqdn + "@" + ipa_realm }}'
    keytab: /etc/httpd/conf/http.keytab
    user: apache
    group: root
    notify: restart katello
    type: service
  realm:
    principal: '{{ "realm-proxy" + "@" + ipa_realm }}'
    keytab: /etc/foreman-proxy/freeipa.keytab
    user: foreman-proxy
    group: foreman-proxy
    notify: restart foreman-proxy
    type: user


# stuff that might be needed for idm dns integration
katello_idm_dns_server: '{{ groups[ipaserver][0] }}'
katello_dns_tsig_principal: '{{ katello_keytabs.foremanproxy.principal }}'
katello_dns_tsig_keytab: '{{ katello_keytabs.foremanproxy.keytab }}'
katello_realm_principal: '{{ katello_keytabs.realm.principal }}'
katello_realm_keytab: '{{ katello_keytabs.realm.keytab }}'

katello_firewall_ports:
  - 69/udp
  - 80/tcp
  - 443/tcp
  - 5000/tcp
  - 5647/tcp
  - 5900-5930/tcp
  - 8000/tcp
  - 9090/tcp
