---
- name: set readable vars
  set_fact:
    image: "{{ guests[os_image]['guest_def']['devices']['storage']['sda']['image'] }}"
    image_pool: "{{ guests[os_image]['guest_def']['devices']['storage']['sda']['pool'] }}"
    backing_image: "{{ guests[os_image]['guest_def']['devices']['storage']['sda']['backing_image'] |
      default( 'backing_' + guests[os_image]['guest_def']['dist'] + guests[os_image]['guest_def']['dist_major'] | string + '_sda.qcow2' ) }}"
    backing_image_pool: "{{ guests[os_image]['guest_def']['devices']['storage']['sda']['backing_image_pool'] | default('default') }}"
    dist_family: "{{ guests[os_image]['guest_def']['dist_family'] }}"

- name: set more readable vars
  set_fact:
    image_pool_path: "{{ ansible_libvirt_pools[image_pool]['path'] }}"
    backing_image_pool_path: "{{ ansible_libvirt_pools[backing_image_pool]['path'] }}"

- name: sparsify image
  command: >-
    /usr/bin/virt-sparsify {{ image_pool_path }}/{{ image }}
    --compress {{ backing_image_pool_path }}/{{ backing_image }}
    --tmp {{ image_pool_path }}
  tags:
    - skip_ansible_lint
