---
# Possible settings are described under the following link:
# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsTimeService::W32TIME_POLICY_CONFIGURE_NTPCLIENT
ntp_time_type: 'NTP'
ntp_crosssitesyncflags: '2'
ntp_resolvepeerbackoffminutes: '15'
ntp_resolvepeerbackoffmaxtimes: '7'
ntp_specialpollinterval: '1024'
ntp_eventlogflags: '0'

# Possible NTP flags that can be used under windows.
# 0x01    SpecialInterval
# 0x02    UseAsFallbackOnly
# 0x04    SymmatricActive
# 0x08    Client
ntp_flag: '0x01'
