---
- block:
    - name: determine {{ guest['key'] }} ip
      command: virsh domifaddr {{ guest['key'] }}
      register: virsh_results
      until: "'ipv4' in virsh_results['stdout']"
      retries: 360
      changed_when: false

    - name: add guest to inventory
      add_host:
        hostname: "{{ guest['key'] }}"
        groups: "{{ guests[guest['key']]['guest_def']['host_groups'] | default(['all']) }}"
        ansible_host: "{{ (virsh_results['stdout'] | regex_findall('^.*ipv4\\s+(.*)/.*$','\\1'))[0]  }}"
  when:
    - guests[guest['key']]['network_connections'][0]['ip']['address'] is not defined

- name: add guest to inventory
  add_host:
    hostname: "{{ guest['key'] }}"
    groups: "{{ guests[guest['key']]['guest_def']['host_groups'] | default(['all']) }}"
    ansible_host: "{{ guests[guest['key']]['network_connections'][0]['ip']['address'][0] | ansible.netcommon.ipaddr('address') }}"
  when:
    - guests[guest['key']]['network_connections'][0]['ip']['address'] is defined
