---
- name: Create Fedora37 backing image
  hosts: buildhost
  gather_facts: true
  remote_user: root
  vars:
    os_image: Fedora37

  tasks:
    - name: Include set vm vars
      ansible.builtin.include_role:
        name: RobVerduijn.lab.set_vm_vars

    - name: Create backing image
      ansible.builtin.include_role:
        name: RobVerduijn.lab.create_backing_image

    - name: Delete {{ os_image }}
      ansible.builtin.include_role:
        name: RobVerduijn.lab.delete_guest
