---
- name: create Fedora35 backing image
  hosts: buildhost
  gather_facts: true
  remote_user: root
  vars:
    os_image: Fedora35

  tasks:
    - name: include set vm vars
      include_role:
        name: RobVerduijn.lab.set_vm_vars

    - name: create backing image
      include_role:
        name: RobVerduijn.lab.create_backing_image

    - name: delete {{ os_image }}
      include_role:
        name: RobVerduijn.lab.delete_guest
