---
- name: Create guest
  hosts: buildhost
  gather_facts: true
  remote_user: root
  vars:

  tasks:
    - name: Set desktop flavor
      ansible.builtin.set_fact:
        desktop: "{{ desktop | default('kde') }}"

    - name: Set linux.lab name to {{ desktop }}
      ansible.builtin.set_fact:
        vms: "{{ [desktop + '.linux.lab'] }}"

    - name: Set desktop var for {{ desktop + '.linux.lab' }}
      ansible.builtin.add_host:
        name: "{{ desktop + '.linux.lab' }}"
        desktop: "{{ desktop }}"

    - name: Include set vm vars
      ansible.builtin.include_role:
        name: RobVerduijn.lab.set_vm_vars

    - name: Delete {{ vms | join(' ') }}
      ansible.builtin.include_role:
        name: RobVerduijn.lab.delete_guest
      when:
        - delete_vm is defined
        - delete_vm | bool

    - name: Create {{ vms | join(' ') }}
      ansible.builtin.include_role:
        name: RobVerduijn.lab.create_guest

    - name: Ensure guests are started
      community.libvirt.virt:
        name: "{{ guest['key'] }}"
        state: running
      loop: "{{ guests | dict2items }}"
      loop_control:
        loop_var: guest

    - name: Add guests to inventory
      ansible.builtin.include_role:
        name: RobVerduijn.lab.add_guest_to_inventory
      loop: "{{ guests | dict2items }}"
      loop_control:
        loop_var: guest

- name: Configure guests
  hosts: "{{ hostvars[groups['buildhost'][0]]['vms'] | default('fail') }}"
  gather_facts: false
  remote_user: root

  tasks:
    - name: Wait for to fully start {{ inventory_hostname }}
      ansible.builtin.wait_for_connection:

    - name: Gather facts
      ansible.builtin.setup:

    # an 'environment group' is not the same as a group
    # it contains quite a lot more packages
    # available desktop environments groups in fedora35:
    #   basic-desktop-environment
    #   cinnamon-desktop-environment
    #   deepin-desktop-environment
    #   i3-desktop-environment
    #   kde-desktop-environment
    #   lxde-desktop-environment
    #   lxqt-desktop-environment
    #   mate-desktop-environment
    #   sugar-desktop-environment
    #   workstation-product-environment
    #   xfce-desktop-environment

    - name: Ensure workstation desktop environment is present
      ansible.builtin.dnf:
        name: '@{{ desktop }}-desktop-environment'
        state: present

    - name: Change default target to graphical.target
      ansible.builtin.file:
        src: /usr/lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link

    - name: Add the user student
      ansible.builtin.user:
        name: "{{ user }}"
        groups: wheel
        password: "{{ user_password | password_hash('sha512') }}"
        append: true

    - name: Include roles
      ansible.builtin.include_role:
        name: "{{ my_role }}"
      loop:
        - RobVerduijn.lab.add_swap_file
        - RobVerduijn.lab.remove_cloud_init
        - RobVerduijn.lab.update
        - fedora.linux_system_roles.network
        - fedora.linux_system_roles.timesync
        - RobVerduijn.lab.conditional_reboot
      loop_control:
        loop_var: my_role

    - name: Ready
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} is ready"
