---
- name: create ipa.linux.lab guest
  hosts: buildhost
  gather_facts: true
  remote_user: root
  vars:
    vms:
      - ipa.linux.lab
  tasks:
    - name: include set vm vars
      include_role:
        name: RobVerduijn.lab.set_vm_vars

    - name: delete {{ vms | join(' ') }}
      include_role:
        name: RobVerduijn.lab.delete_guest
      when:
        - delete_vm is defined
        - delete_vm | bool

    - name: create {{ vms | join(' ') }}
      include_role:
        name: RobVerduijn.lab.create_guest

    - name: ensure guests are started
      community.libvirt.virt:
        name: "{{ guest['key'] }}"
        state: running
      loop: "{{ guests | dict2items }}"
      loop_control:
        loop_var: guest

    - name: add guests to inventory
      include_role:
        name: RobVerduijn.lab.add_guest_to_inventory
      loop: "{{ guests | dict2items }}"
      loop_control:
        loop_var: guest

- name: configure ipaserver
  hosts: ipaserver
  gather_facts: false
  remote_user: root

  tasks:
    - name: wait for {{ inventory_hostname }} to fully start
      wait_for_connection:

    - name: gather facts
      setup:

    # ipa dns does not work yet
    # so configuring the resolv.conf to
    # forward to the libvirt network dns
    - name: temporary overide dns config
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 192.168.100.1
        mode: 0644

    - name: update system
      package:
        name: '*'
        state: latest
      tags:
        - skip_ansible_lint

    - name: configure ipaserver
      include_role:
        name: freeipa.ansible_freeipa.ipaserver

    - name: include roles
      include_role:
        name: "{{ item }}"
      loop:
        - RobVerduijn.lab.add_swap_file
        - RobVerduijn.lab.remove_cloud_init
        - RobVerduijn.lab.conditional_reboot
        - fedora.linux_system_roles.network
        - fedora.linux_system_roles.timesync

    - name: ready
      debug:
        msg: "{{ inventory_hostname }} is ready"
