---
- name: Create centos8stream.linux.lab guest
  hosts: buildhost
  gather_facts: true
  remote_user: root
  vars:
    vms:
      - centos8_stream.linux.lab
  tasks:
    - name: Include set vm vars
      ansible.builtin.include_role:
        name: RobVerduijn.lab.set_vm_vars

    - name: Delete {{ vms | join(' ') }}
      ansible.builtin.include_role:
        name: RobVerduijn.lab.delete_guest
      when:
        - delete_vm is defined
        - delete_vm | bool

    - name: Create {{ vms | join(' ') }}
      ansible.builtin.include_role:
        name: RobVerduijn.lab.create_guest

    - name: Ensure guests are started
      community.libvirt.virt:
        name: "{{ guest['key'] }}"
        state: running
      loop: "{{ guests | dict2items }}"
      loop_control:
        loop_var: guest

    - name: Add guests to inventory
      ansible.builtin.include_role:
        name: RobVerduijn.lab.add_guest_to_inventory
      loop: "{{ guests | dict2items }}"
      loop_control:
        loop_var: guest

- name: Configure rocky
  hosts: centos8_stream.linux.lab
  gather_facts: false
  remote_user: root

  tasks:
    - name: Wait for system to fully start
      ansible.builtin.wait_for_connection:

    - name: Gather facts
      ansible.builtin.setup:

    - name: Include roles
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop:
        - RobVerduijn.lab.add_swap_file
        - RobVerduijn.lab.remove_cloud_init
        - fedora.linux_system_roles.network
        - fedora.linux_system_roles.timesync
        - RobVerduijn.lab.update
        - RobVerduijn.lab.conditional_reboot
      loop_control:
        loop_var: role

    - name: Ready
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} is ready"
