---
- name: Create standalone katello system
  hosts: buildhost
  gather_facts: true
  remote_user: root
  diff: true
  vars:
    vms:
      - katello.linux.lab
  tasks:
    - name: Include set vm vars
      ansible.builtin.include_role:
        name: RobVerduijn.lab.set_vm_vars

    - name: Ensure guests are started
      community.libvirt.virt:
        name: "{{ guest['key'] }}"
        state: running
      loop: "{{ guests | dict2items }}"
      loop_control:
        loop_var: guest

    - name: Add guests to inventory
      ansible.builtin.include_role:
        name: RobVerduijn.lab.add_guest_to_inventory
      loop: "{{ guests | dict2items }}"
      loop_control:
        loop_var: guest

- name: Customize katello server
  hosts: katello.linux.lab
  gather_facts: false
  remote_user: root

  tasks:
    - name: Wait for system to fully start
      ansible.builtin.wait_for_connection:

    - name: Gather facts
      ansible.builtin.setup:

    - name: Include roles
      ansible.builtin.include_role:
        name: "{{ role_name }}"
      loop:
        - RobVerduijn.lab.katello
      loop_control:
        loop_var: role_name
      vars:
        foreman_configure_infrastructure: false
