---
- name: Create Fedora backing image
  hosts: buildhost
  gather_facts: true
  remote_user: root

  tasks:
    - name: Set os group
      ansible.builtin.group_by:
        key: "{{ ansible_distribution }}"

    - name: Set os group version
      ansible.builtin.group_by:
        key: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}"
        parents:
          - "{{ ansible_distribution }}"

    - name: Set os_image
      ansible.builtin.set_fact:
        os_image: "{{ dist | default(ansible_distribution) }}{{ release | default(ansible_distribution_major_version) }}"

    - name: Include set vm vars
      ansible.builtin.include_role:
        name: RobVerduijn.lab.set_vm_vars

    - name: Create backing image
      ansible.builtin.include_role:
        name: RobVerduijn.lab.create_backing_image

    - name: Delete {{ os_image }}
      ansible.builtin.include_role:
        name: RobVerduijn.lab.delete_guest
