---
- name: create standalone katello system
  hosts: buildhost
  gather_facts: true
  remote_user: root
  vars:
    vms:
      - katello.linux.lab
  tasks:
    - name: include set vm vars
      include_role:
        name: RobVerduijn.lab.set_vm_vars

    - name: delete {{ vms | join(' ') }}
      include_role:
        name: RobVerduijn.lab.delete_guest
      when:
        - delete_vm is defined
        - delete_vm | bool

    - name: create {{ vms | join(' ') }}
      include_role:
        name: RobVerduijn.lab.create_guest

    - name: ensure guests are started
      community.libvirt.virt:
        name: "{{ guest['key'] }}"
        state: running
      loop: "{{ guests | dict2items }}"
      loop_control:
        loop_var: guest

    - name: add guests to inventory
      include_role:
        name: RobVerduijn.lab.add_guest_to_inventory
      loop: "{{ guests | dict2items }}"
      loop_control:
        loop_var: guest

- name: customize katello server
  hosts: katello.linux.lab
  gather_facts: false
  remote_user: root
  environment:
    FOREMAN_PASSWORD: "{{ foreman_installer_option_admin_password }}"
    FOREMAN_SERVER_URL: https://{{ inventory_hostname }}
    FOREMAN_USERNAME: "{{ foreman_installer_option_admin }}"
    FOREMAN_VALIDATE_CERTS: false

  tasks:
    - name: wait for {{ inventory_hostname }} to fully start
      wait_for_connection:

    - name: gather facts
      setup:

    - name: update system
      package:
        name: '*'
        state: latest
      tags:
        - skip_ansible_lint

    - name: include roles
      include_role:
        name: "{{ role_name }}"
      loop:
        - RobVerduijn.lab.add_swap_file
        - RobVerduijn.lab.remove_cloud_init
        - RobVerduijn.lab.conditional_reboot
        - fedora.linux_system_roles.network
        - fedora.linux_system_roles.timesync
        - RobVerduijn.lab.katello
      loop_control:
        loop_var: role_name
      vars:
        swap_file_size_mb: 4096  # MiB

