---
- name: create ipa lab guests
  hosts: buildhost
  gather_facts: true
  remote_user: root
  vars:
    vms:
      - ipa.linux.lab
      - ipaclient.linux.lab
  tasks:
    - name: Include set vm vars
      ansible.builtin.include_role:
        name: RobVerduijn.lab.set_vm_vars

    - name: Delete {{ vms | join(' ') }}
      ansible.builtin.include_role:
        name: RobVerduijn.lab.delete_guest
      when:
        - delete_vm is defined
        - delete_vm | bool

    - name: Create {{ vms | join(' ') }}
      ansible.builtin.include_role:
        name: RobVerduijn.lab.create_guest

    - name: Ensure guests are started
      community.libvirt.virt:
        name: "{{ guest['key'] }}"
        state: running
      loop: "{{ guests | dict2items }}"
      loop_control:
        loop_var: guest

    - name: Add guests to inventory
      ansible.builtin.include_role:
        name: RobVerduijn.lab.add_guest_to_inventory
      loop: "{{ guests | dict2items }}"
      loop_control:
        loop_var: guest

- name: Configure ipaserver
  hosts: ipaserver
  gather_facts: false
  remote_user: root

  tasks:
    - name: Wait for host to fully start
      ansible.builtin.wait_for_connection:

    - name: Gather facts
      ansible.builtin.setup:

    - name: Get service on port 53
      ansible.builtin.command: ss -tulpen
      register: results
      when: true

    # ipa dns does not work yet
    # so configuring the resolv.conf to
    # forward to the libvirt network dns
    - name: Temporary overide dns config
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 192.168.100.1
        mode: 0644
      when: "'named' not in results['stdout']"

    - name: Include roles
      ansible.builtin.include_role:
        name: "{{ my_role }}"
      loop:
        - RobVerduijn.lab.add_swap_file
        - RobVerduijn.lab.remove_cloud_init
        - RobVerduijn.lab.update
        - RobVerduijn.lab.conditional_reboot
        - freeipa.ansible_freeipa.ipaserver
        - fedora.linux_system_roles.network
        - fedora.linux_system_roles.timesync
      loop_control:
        loop_var: my_role

    - name: Add student user
      freeipa.ansible_freeipa.ipauser:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: student
        first: Student
        last: User
        password: "student"
        update_password: on_create

    - name: Ready message
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} is ready"

- name: Configure ipaserver
  hosts: ipaclients
  gather_facts: false
  remote_user: root

  tasks:
    - name: Wait for host to fully start
      ansible.builtin.wait_for_connection:

    - name: Gather facts
      ansible.builtin.setup:

    - name: Ensure workstation desktop environment is present
      ansible.builtin.dnf:
        name: '@workstation-product-environment'
        state: present

    - name: Change default target to graphical.target
      ansible.builtin.file:
        src: /usr/lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link

    - name: Include roles
      ansible.builtin.include_role:
        name: "{{ my_role }}"
      loop:
        - RobVerduijn.lab.add_swap_file
        - RobVerduijn.lab.remove_cloud_init
        - RobVerduijn.lab.update
        - fedora.linux_system_roles.network
        - fedora.linux_system_roles.timesync
        - freeipa.ansible_freeipa.ipaclient
        - RobVerduijn.lab.conditional_reboot
      loop_control:
        loop_var: my_role

    - name: Ready message
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} is ready"
