---
- name: create lxde.linux.lab guest
  hosts: buildhost
  gather_facts: true
  remote_user: root
  vars:
    vms:
      - lxde.linux.lab

  tasks:
    - name: include set vm vars
      include_role:
        name: RobVerduijn.lab.set_vm_vars

    - name: delete {{ vms | join(' ') }}
      include_role:
        name: RobVerduijn.lab.delete_guest
      when:
        - delete_vm is defined
        - delete_vm | bool

    - name: create {{ vms | join(' ') }}
      include_role:
        name: RobVerduijn.lab.create_guest

    - name: ensure guests are started
      community.libvirt.virt:
        name: "{{ guest['key'] }}"
        state: running
      loop: "{{ guests | dict2items }}"
      loop_control:
        loop_var: guest

    - name: add guests to inventory
      include_role:
        name: RobVerduijn.lab.add_guest_to_inventory
      loop: "{{ guests | dict2items }}"
      loop_control:
        loop_var: guest

- name: configure guests
  hosts: "{{ hostvars[groups['buildhost'][0]]['vms'] | default('fail') }}"
  gather_facts: false
  remote_user: root

  tasks:
    - name: wait for {{ inventory_hostname }} to fully start
      wait_for_connection:
    
    - name: gather facts
      setup:

    - name: ensure workstation desktop environment is present
      package:
        name: '@lxde-desktop-environment'
        state: present

    - name: Change default target to graphical.target
      file:
        src: /usr/lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link

    - name: Add the user student
      ansible.builtin.user:
        name: "{{ user }}"
        groups: wheel
        password: "{{ user_password | password_hash('sha512') }}"
        append: yes

    - name: include roles
      include_role:
        name: "{{ my_role }}"
      loop:
        - RobVerduijn.lab.add_swap_file
        - RobVerduijn.lab.remove_cloud_init
        - RobVerduijn.lab.update
        - fedora.linux_system_roles.network
        - fedora.linux_system_roles.timesync
        - RobVerduijn.lab.conditional_reboot
      loop_control:
        loop_var: my_role

    - name: ready
      debug:
        msg: "{{ inventory_hostname }} is ready"