---
- name: delete linux.lab guests
  hosts: buildhost
  gather_facts: true
  remote_user: root
  vars:
    vms:
      - centos8.linux.lab
      - centos8stream.linux.lab
      - kde.linux.lab
      - lxde.linux.lab
      - rocky8.linux.lab
      - fedora34.linux.lab
      - fedora35.linux.lab

  tasks:
    - name: include set vm vars
      include_role:
        name: RobVerduijn.lab.set_vm_vars

    - name: delete {{ vms | join(' ') }}
      include_role:
        name: RobVerduijn.lab.delete_guest
