---
- name: setup ansible controller
  hosts: buildhost
  become: false

  tasks:
    - name: check if there is only one buildhost
      assert:
        that:
          - groups['buildhost'] | length == 1
        fail_msg: There should only be one host in the buildhost group
        success_msg: The buildhost is {{ inventory_hostname }}

    - name: install required packages
      package:
        name:
          - genisoimage
          - python3-virtualenv
          - virtio-win
        state: present
      remote_user: root

    - name: ensure symlink to iso is present in default images folder
      file:
        src: /usr/share/virtio-win/virtio-win.iso
        dest: /var/lib/libvirt/images/virtio-win.iso
        state: link
        owner: qemu
        group: qemu
        setype: virt_content_t
        mode: 0644
      remote_user: root

    - name: debug vars
      debug:
        var: playbook_dir

    - name: debug vars
      debug:
        var: ansible_version

    - name: create venv dir
      file:
        path: "{{ playbook_dir }}/venv"
        state: directory
        mode: 0700

    - name: create requirements.txt
      copy:
        dest: "{{ playbook_dir }}/venv/requirements.txt"
        content: |
          ansible-core
          ansible-lint
          jmespath
          netaddr
          ntlm-auth
          pip
          pywinrm
          requests
          requests-ntlm
          selinux
        mode: 0600

    - name: Initiate virtualenv
      pip:
        virtualenv: "{{ playbook_dir }}/venv"
        requirements: "{{ playbook_dir }}/venv/requirements.txt"
        extra_args: --upgrade

    - name: install collections and roles
      shell: |
        ansible-galaxy collection install -f --force-with-deps git+https://github.com/RobVerduijn/lab.git
      when: true

    - name: add networks
      include_role:
        name: RobVerduijn.lab.create_network
