---
- name: setup ansible controller
  hosts: buildhost
  become: false

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
      when: ansible_facts['packages'] is not defined

    - name: Check if there is only one buildhost
      ansible.builtin.assert:
        that:
          - groups['buildhost'] | length == 1
        fail_msg: There should only be one host in the buildhost group
        success_msg: The buildhost is {{ inventory_hostname }}

    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - genisoimage
          - python3-jmespath
          - python3-pip
          - python3-virtualenv
          - virtio-win
        state: present
      remote_user: root
      when: >-
        ['genisoimage', 'python3-jmespath', 'python3-pip', 'python3-virtualenv', 'virtio-win']
        | difference(ansible_facts['packages'].keys()) | length > 0

    - name: Ensure symlink to iso is present in default images folder
      ansible.builtin.file:
        src: /usr/share/virtio-win/virtio-win.iso
        dest: /var/lib/libvirt/images/virtio-win.iso
        state: link
        owner: qemu
        group: qemu
        setype: virt_content_t
        mode: 0644
      remote_user: root

    - name: Show playbook dir
      ansible.builtin.debug:
        var: playbook_dir

    - name: Show ansible version
      ansible.builtin.debug:
        var: ansible_version

    - name: Create venv dir
      ansible.builtin.file:
        path: "{{ playbook_dir }}/venv"
        state: directory
        mode: 0700

    - name: Create requirements.txt
      ansible.builtin.copy:
        dest: "{{ playbook_dir }}/venv/requirements.txt"
        content: |
          ansible-core
          ansible-lint
          jmespath
          netaddr
          ntlm-auth
          pip
          pywinrm
          requests
          requests-ntlm
          selinux
        mode: 0600

    - name: Initiate virtualenv
      ansible.builtin.pip:
        virtualenv: "{{ playbook_dir }}/venv"
        requirements: "{{ playbook_dir }}/venv/requirements.txt"
        extra_args: --upgrade

    - name: Install lab collection
      ansible.builtin.shell: |
        ansible-galaxy collection install -U -p collections git+https://github.com/RobVerduijn/lab.git

    - name: Add networks
      ansible.builtin.include_role:
        name: RobVerduijn.lab.create_network
